// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock

import (
	models "api/app/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTodoRepository is an autogenerated mock type for the TodoRepository type
type MockTodoRepository struct {
	mock.Mock
}

type MockTodoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoRepository) EXPECT() *MockTodoRepository_Expecter {
	return &MockTodoRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: title, description, priority
func (_m *MockTodoRepository) Create(title string, description string, priority string) (*models.Todo, error) {
	ret := _m.Called(title, description, priority)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*models.Todo, error)); ok {
		return rf(title, description, priority)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *models.Todo); ok {
		r0 = rf(title, description, priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(title, description, priority)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTodoRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - title string
//   - description string
//   - priority string
func (_e *MockTodoRepository_Expecter) Create(title interface{}, description interface{}, priority interface{}) *MockTodoRepository_Create_Call {
	return &MockTodoRepository_Create_Call{Call: _e.mock.On("Create", title, description, priority)}
}

func (_c *MockTodoRepository_Create_Call) Run(run func(title string, description string, priority string)) *MockTodoRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTodoRepository_Create_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_Create_Call) RunAndReturn(run func(string, string, string) (*models.Todo, error)) *MockTodoRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockTodoRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTodoRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockTodoRepository_Expecter) Delete(id interface{}) *MockTodoRepository_Delete_Call {
	return &MockTodoRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockTodoRepository_Delete_Call) Run(run func(id int)) *MockTodoRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTodoRepository_Delete_Call) Return(_a0 error) *MockTodoRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoRepository_Delete_Call) RunAndReturn(run func(int) error) *MockTodoRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockTodoRepository) GetAll() ([]models.Todo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Todo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Todo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTodoRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockTodoRepository_Expecter) GetAll() *MockTodoRepository_GetAll_Call {
	return &MockTodoRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockTodoRepository_GetAll_Call) Run(run func()) *MockTodoRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTodoRepository_GetAll_Call) Return(_a0 []models.Todo, _a1 error) *MockTodoRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_GetAll_Call) RunAndReturn(run func() ([]models.Todo, error)) *MockTodoRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockTodoRepository) GetByID(id int) (*models.Todo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Todo); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTodoRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *MockTodoRepository_Expecter) GetByID(id interface{}) *MockTodoRepository_GetByID_Call {
	return &MockTodoRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockTodoRepository_GetByID_Call) Run(run func(id int)) *MockTodoRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTodoRepository_GetByID_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_GetByID_Call) RunAndReturn(run func(int) (*models.Todo, error)) *MockTodoRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, title, description, priority, completed
func (_m *MockTodoRepository) Update(id int, title string, description string, priority string, completed *bool) (*models.Todo, error) {
	ret := _m.Called(id, title, description, priority, completed)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string, string, string, *bool) (*models.Todo, error)); ok {
		return rf(id, title, description, priority, completed)
	}
	if rf, ok := ret.Get(0).(func(int, string, string, string, *bool) *models.Todo); ok {
		r0 = rf(id, title, description, priority, completed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string, string, string, *bool) error); ok {
		r1 = rf(id, title, description, priority, completed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTodoRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id int
//   - title string
//   - description string
//   - priority string
//   - completed *bool
func (_e *MockTodoRepository_Expecter) Update(id interface{}, title interface{}, description interface{}, priority interface{}, completed interface{}) *MockTodoRepository_Update_Call {
	return &MockTodoRepository_Update_Call{Call: _e.mock.On("Update", id, title, description, priority, completed)}
}

func (_c *MockTodoRepository_Update_Call) Run(run func(id int, title string, description string, priority string, completed *bool)) *MockTodoRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(string), args[3].(string), args[4].(*bool))
	})
	return _c
}

func (_c *MockTodoRepository_Update_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_Update_Call) RunAndReturn(run func(int, string, string, string, *bool) (*models.Todo, error)) *MockTodoRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTodoRepository creates a new instance of MockTodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoRepository {
	mock := &MockTodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
