/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * A simple todo API built with Go and Gin framework
 * OpenAPI spec version: 1.0
 */

import type { GetApiV1TodosId200AllOf } from './getApiV1TodosId200AllOf'
import type { HandlerAPIResponse } from './handlerAPIResponse'

export type GetApiV1TodosId200 = HandlerAPIResponse & GetApiV1TodosId200AllOf
