/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * A simple todo API built with Go and Gin framework
 * OpenAPI spec version: 1.0
 */

import type { GetHealth200AllOf } from './getHealth200AllOf'
import type { HandlerHealthResponse } from './handlerHealthResponse'

export type GetHealth200 = HandlerHealthResponse & GetHealth200AllOf
