/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * Health check response structure
 * OpenAPI spec version: 1.0
 */

/**
 * A simple todo API built with Go and Gin framework
 */
export interface MainHealthResponse {
  message: string
  status: string
}
