/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * A simple todo API built with Go and Gin framework
 * OpenAPI spec version: 1.0
 */
import type { ModelsTodoPriority } from './modelsTodoPriority'

export interface ModelsTodo {
  completed?: boolean
  created_at: string
  description?: string
  id: number
  priority: ModelsTodoPriority
  title: string
  updated_at: string
}
