/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * A simple todo API built with Go and Gin framework
 * OpenAPI spec version: 1.0
 */

export type ModelsTodoPriority = (typeof ModelsTodoPriority)[keyof typeof ModelsTodoPriority]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsTodoPriority = {
  PriorityLow: 'low',
  PriorityMedium: 'medium',
  PriorityHigh: 'high',
} as const
