/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * A simple todo API built with Go and Gin framework
 * OpenAPI spec version: 1.0
 */

export interface ModelsAPIResponse {
  data?: unknown
  message?: string
}
