/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * A simple todo API built with Go and Gin framework
 * OpenAPI spec version: 1.0
 */
import type { HandlerAPIResponse } from './handlerAPIResponse'
import type { PostApiV1Todos201AllOf } from './postApiV1Todos201AllOf'

export type PostApiV1Todos201 = HandlerAPIResponse & PostApiV1Todos201AllOf
