/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * A simple todo API built with Go and Gin framework
 * OpenAPI spec version: 1.0
 */
import type { HandlerAPIResponse } from './handlerAPIResponse'
import type { PutApiV1TodosId200AllOf } from './putApiV1TodosId200AllOf'

export type PutApiV1TodosId200 = HandlerAPIResponse & PutApiV1TodosId200AllOf
