/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * A simple todo API built with Go and Gin framework
 * OpenAPI spec version: 1.0
 */
import type { RequestCreateTodoRequestPriority } from './requestCreateTodoRequestPriority'

export interface RequestCreateTodoRequest {
  /** @maxLength 500 */
  description?: string
  priority?: RequestCreateTodoRequestPriority
  /** @maxLength 100 */
  title: string
}
