/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Todo API
 * A simple todo API built with Go and Gin framework
 * OpenAPI spec version: 1.0
 */

export type ResponseTodoResponsePriority =
  (typeof ResponseTodoResponsePriority)[keyof typeof ResponseTodoResponsePriority]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseTodoResponsePriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const
