with-expecter: true
dir: "mocks"
packages:
  api/repository:
    interfaces:
      TodoRepository:
        config:
          dir: "app/repository/mock"
          filename: "TodoRepository.go"
          mockname: "MockTodoRepository"
          outpkg: "mock"
  api/app/external:
    interfaces:
      NotificationClient:
        config:
          dir: "app/external/mock"
          filename: "NotificationClient.go"
          mockname: "MockNotificationClient"
          outpkg: "mock"