version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: api_postgres
    environment:
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: apipassword
      POSTGRES_DB: apidb
    ports:
      - "9000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apiuser -d apidb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: