# 継続的インテグレーション（CI）ワークフロー
# main以外のブランチへのpushとmainへのPRで自動テスト実行
name: Continuous Integration

on:
  push:
    branches-ignore:
      - main # main以外の全ブランチでトリガー
  pull_request:
    branches:
      - main

jobs:
  # ===== 品質チェック（Turborepo + テスト） =====
  # 再利用可能ワークフローを使用してTurboビルド・テストを実行
  test:
    uses: "./.github/workflows/test-reusable.yml"
    with:
      test-db-password: "test_password"
