# 継続的インテグレーション（CI）ワークフロー
# main以外のブランチへのpushとmainへのPRで自動テスト実行
name: Continuous Integration

on:
  pull_request:

jobs:
  # ===== 品質チェック（Turborepo + テスト） =====
  # 再利用可能ワークフローを使用してTurboビルド・テストを実行
  test:
    uses: "./.github/workflows/test-reusable.yml"
    with:
      test-db-password: "test_password"
