name: Deploy Full Stack to Production
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      message:
        description: "Production deployment message"
        required: false
        type: string
        default: "Manual full stack deployment to production environment"

jobs:
  # Step 1: テスト実行（再利用可能ワークフローを使用）
  run-tests:
    uses: "./.github/workflows/test-reusable.yml"
    with:
      test-db-password: "prod_test_password"

  # Step 2: テスト成功後のデプロイ
  deploy:
    needs: [run-tests] # ← テスト成功必須
    permissions:
      contents: read
      id-token: write
    uses: "./.github/workflows/fullstack-deploy-reusable.yml"
    with:
      ENVIRONMENT: prod
      PROJECT_ID: terraform-gcp-466623
      REGION: asia-northeast1
      VPC_CONNECTOR_NAME: main-connector
      API_SERVICE_NAME: api-service-prod
      DASHBOARD_SERVICE_NAME: dashboard-service-prod
      API_BASE_URL: https://api.my-learn-iac-sample.site
      DASHBOARD_BASE_URL: https://dashboard.my-learn-iac-sample.site
    secrets:
      db-password: ${{ secrets.PROD_DB_PASSWORD }}
      wif-provider: ${{ secrets.PROD_WIF_PROVIDER }}
      service-account: ${{ secrets.PROD_SERVICE_ACCOUNT }}
      gcs-bucket-name: ${{ secrets.PROD_GCS_BUCKET_NAME }}
      cdn-url-map-name: ${{ secrets.PROD_CDN_URL_MAP_NAME }}