# フルスタックアプリケーション開発環境デプロイワークフロー
# APIとダッシュボードの変更検出時に自動でdev環境へデプロイ実行
name: Deploy Full Stack to Dev
on:
  # 手動実行オプション
  workflow_dispatch:
    inputs:
      message:
        description: "Deployment message"
        required: false
        type: string
        default: "Manual full stack deployment to dev environment"

jobs:
  # ===== ダイレクトデプロイ（テストは別のciで事前に実行をする） =====
  # テスト処理をスキップして直接デプロイを実行
  deploy:
    permissions:
      contents: read # リポジトリ読み取り権限
      id-token: write # OIDC トークン生成権限（Workload Identity用）
    # 再利用可能ワークフローを呼び出し（実際のデプロイ処理）
    uses: "./.github/workflows/fullstack-deploy-reusable.yml"
    with:
      # デプロイ環境設定
      ENVIRONMENT: dev
      PROJECT_ID: my-fourth-dev
      REGION: asia-northeast1
      VPC_CONNECTOR_NAME: api-connector
      # Cloud Runサービス名
      API_SERVICE_NAME: api-service
      # 公開URL
      API_BASE_URL: https://dev.api.my-learn-iac-sample.site
      DASHBOARD_CLIENT_URL: https://dev.dashboard.my-learn-iac-sample.site
      # データベース接続情報
      DB_HOST: "10.187.144.5"
      DB_USER: "api_user"
      DB_NAME: "api_db"
      # 非機密設定値
      WIF_PROVIDER: projects/743590720330/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
      SERVICE_ACCOUNT: github-actions-deployer@my-fourth-dev.iam.gserviceaccount.com
      GCS_BUCKET_NAME: my-fourth-dev-dashboard-frontend-542a29f1
    secrets:
      # 機密情報のみ
      DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
