# フルスタックアプリケーション本番環境デプロイワークフロー
# mainブランチへのマージ時に自動でprod環境へデプロイ実行
name: Deploy Full Stack to Production

on:
  # 手動実行オプション
  workflow_dispatch:
    inputs:
      message:
        description: "Deployment message"
        required: false
        type: string
        default: "Manual full stack deployment to prod environment"

# mainブランチへのプッシュ（マージ）時に自動実行（現在は無効化）
# push:
#   branches:
#     - main
#   paths:
#     - "apps/api/**"
#     - "apps/dashboard/**"
#     - ".github/workflows/**"

jobs:
  # ===== 本番デプロイ =====
  # 本番環境への慎重なデプロイを実行
  deploy:
    permissions:
      contents: read # リポジトリ読み取り権限
      id-token: write # OIDC トークン生成権限（Workload Identity用）
    # 再利用可能ワークフローを呼び出し（実際のデプロイ処理）
    uses: "./.github/workflows/fullstack-deploy-reusable.yml"
    with:
      # デプロイ環境設定
      ENVIRONMENT: prod
      PROJECT_ID: my-fourth-prod
      REGION: asia-northeast1
      VPC_CONNECTOR_NAME: api-connector
      # Cloud Runサービス名
      API_SERVICE_NAME: api-service
      # 公開URL
      API_BASE_URL: https://api.my-learn-iac-sample.site
      DASHBOARD_CLIENT_URL: https://dashboard.my-learn-iac-sample.site
      # データベース接続情報（terraform outputから取得）
      DB_HOST: "172.28.192.5"
      DB_USER: "api_user"
      DB_NAME: "api_db"
      # 非機密設定値
      WIF_PROVIDER: projects/61528103341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
      SERVICE_ACCOUNT: github-actions-deployer@my-fourth-prod.iam.gserviceaccount.com
      GCS_BUCKET_NAME: my-fourth-prod-dashboard-frontend-81abedbd
